"""changed token names

Revision ID: 0b74f35ca467
Revises: cf91d594e486
Create Date: 2026-05-15 18:21:45.929541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b74f35ca467'
down_revision = 'cf91d594e486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_tokens', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('uncommon_tokens', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('rare_tokens', sa.Integer(), nullable=False, server_default='0'))
        batch_op.drop_column('rare_token')
        batch_op.drop_column('common_token')
        batch_op.drop_column('uncommon_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uncommon_token', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('common_token', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rare_token', sa.INTEGER(), nullable=True))
        batch_op.drop_column('rare_tokens')
        batch_op.drop_column('uncommon_tokens')
        batch_op.drop_column('common_tokens')

    # ### end Alembic commands ###
