"""add dungeon tokens to user

Revision ID: 153691204411
Revises: 3f09bb8331fb
Create Date: 2026-05-09 20:59:54.281085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153691204411'
down_revision = '3f09bb8331fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('easy_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('medium_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hard_tokens', sa.Integer(), nullable=True))
        batch_op.alter_column('gold',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gold',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('hard_tokens')
        batch_op.drop_column('medium_tokens')
        batch_op.drop_column('easy_tokens')

    # ### end Alembic commands ###
