"""add receiver_viewed to trade, remove has_notifications

Revision ID: 25a0bede910b
Revises: c3c28ec81328
Create Date: 2026-05-13 01:01:19.408283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a0bede910b'
down_revision = 'c3c28ec81328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_viewed', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_trade_notification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_trade_notification', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('receiver_viewed')

    # ### end Alembic commands ###
