"""Changed Deck to use UserCard

Revision ID: 3c72ddb3e6f3
Revises: e43a86e2150d
Create Date: 2026-04-30 23:58:52.385175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c72ddb3e6f3'
down_revision = 'e43a86e2150d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_card_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_deck_card_card_id'))
        batch_op.drop_constraint(batch_op.f('unique_card_per_deck'), type_='unique')
        batch_op.create_unique_constraint('unique_card_per_deck', ['deck_id', 'user_card_id'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_card', ['user_card_id'], ['id'])
        batch_op.drop_column('card_id')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deck_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('card_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'card', ['card_id'], ['id'])
        batch_op.drop_constraint('unique_card_per_deck', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_card_per_deck'), ['deck_id', 'card_id'])
        batch_op.create_index(batch_op.f('ix_deck_card_card_id'), ['card_id'], unique=False)
        batch_op.drop_column('user_card_id')

    # ### end Alembic commands ###
