"""add gold to user

Revision ID: 3f09bb8331fb
Revises: 3c72ddb3e6f3
Create Date: 2026-05-02 22:50:29.926964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f09bb8331fb'
down_revision = '3c72ddb3e6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gold')

    # ### end Alembic commands ###
