"""add daily shop purchase table

Revision ID: 4faab23c5d71
Revises: 153691204411
Create Date: 2026-05-10 17:00:21.876828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4faab23c5d71'
down_revision = '153691204411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_shop_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', 'date', name='unique_daily_shop_card')
    )
    with op.batch_alter_table('daily_shop_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_shop_card_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_shop_card_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_shop_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_shop_card_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_shop_card_card_id'))

    op.drop_table('daily_shop_card')
    # ### end Alembic commands ###
