"""update life_time_stats

Revision ID: 70eb614c4840
Revises: fb1e318a05ad
Create Date: 2026-05-15 21:35:51.646947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70eb614c4840'
down_revision = 'fb1e318a05ad'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('life_time_stats', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'games_played',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        batch_op.add_column(
            sa.Column(
                'wins',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        batch_op.add_column(
            sa.Column(
                'losses',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        batch_op.add_column(
            sa.Column(
                'fastest_win_turns',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.add_column(
            sa.Column(
                'score',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        batch_op.drop_index(batch_op.f('ix_life_time_stats_user_id'))
        batch_op.create_index(
            batch_op.f('ix_life_time_stats_user_id'),
            ['user_id'],
            unique=True
        )

        batch_op.drop_column('success')
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column(
            'common_tokens',
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("'0'")
        )

        batch_op.alter_column(
            'uncommon_tokens',
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("'0'")
        )

        batch_op.alter_column(
            'rare_tokens',
            existing_type=sa.INTEGER(),
            nullable=True,
            existing_server_default=sa.text("'0'")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rare_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('uncommon_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('common_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('life_time_stats', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'difficulty',
                sa.VARCHAR(length=20),
                nullable=False,
                server_default='normal'
            )
        )

        batch_op.add_column(
            sa.Column(
                'success',
                sa.BOOLEAN(),
                nullable=False,
                server_default=sa.false()
            )
        )

        batch_op.drop_index(batch_op.f('ix_life_time_stats_user_id'))
        batch_op.create_index(
            batch_op.f('ix_life_time_stats_user_id'),
            ['user_id'],
            unique=False
        )

        batch_op.drop_column('score')
        batch_op.drop_column('fastest_win_turns')
        batch_op.drop_column('losses')
        batch_op.drop_column('wins')
        batch_op.drop_column('games_played')

    # ### end Alembic commands ###
