"""empty message

Revision ID: 759405463a01
Revises: 5adb974016b9
Create Date: 2026-05-15 02:31:54.533353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759405463a01'
down_revision = '5adb974016b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_game'))
        batch_op.drop_index(batch_op.f('ix_game_user_id'))

    op.drop_table('game')
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_user_id'))

    op.drop_table('stats')
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='tradestatus', native_enum=False), nullable=False))
        batch_op.drop_column('receiver_viewed')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.VARCHAR(length=256), server_default=sa.text("'default.png'"), nullable=False))

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_viewed', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.drop_column('status')

    op.create_table('stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stats_user_id'), ['user_id'], unique=False)

    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_user_id'), ['user_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_game_game'), ['game'], unique=False)

    # ### end Alembic commands ###
