"""empty message

Revision ID: 8701d957134e
Revises: f15bb47f3a5a
Create Date: 2026-05-15 02:09:24.079033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8701d957134e'
down_revision = 'f15bb47f3a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=8), nullable=False))

    # ### end Alembic commands ###
