"""drop status from trade

Revision ID: ab9ebdd22fd7
Revises: aeda58166f1b
Create Date: 2026-05-16 01:56:12.560953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9ebdd22fd7'
down_revision = 'aeda58166f1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=8), nullable=False, server_default='pending'))

    # ### end Alembic commands ###
