"""add receiver_viewed to trade

Revision ID: aeda58166f1b
Revises: 6f6d5c84812e
Create Date: 2026-05-15 23:56:48.372271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeda58166f1b'
down_revision = '6f6d5c84812e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_viewed', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('common_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('uncommon_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('rare_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rare_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('uncommon_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('common_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('receiver_viewed')

    # ### end Alembic commands ###
