"""added game score

Revision ID: bca4f954ed49
Revises: 70eb614c4840
Create Date: 2026-05-16 16:00:27.285099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca4f954ed49'
down_revision = '70eb614c4840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.drop_column('score')

    # ### end Alembic commands ###
