"""empty message

Revision ID: c3c28ec81328
Revises: 5adb974016b9
Create Date: 2026-05-13 00:09:50.433822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c28ec81328'
down_revision = '5adb974016b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_trade_notification', sa.Boolean(), nullable=False, server_default=sa.false()))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_trade_notification')

    # ### end Alembic commands ###
