"""empty message

Revision ID: cf91d594e486
Revises: eb7084117355
Create Date: 2026-05-15 18:18:50.781112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf91d594e486'
down_revision = 'eb7084117355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_token', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('uncommon_token', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rare_token', sa.Integer(), nullable=True))
        batch_op.drop_column('hard_tokens')
        batch_op.drop_column('medium_tokens')
        batch_op.drop_column('easy_tokens')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('easy_tokens', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('medium_tokens', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('hard_tokens', sa.INTEGER(), nullable=True))
        batch_op.drop_column('rare_token')
        batch_op.drop_column('uncommon_token')
        batch_op.drop_column('common_token')

    # ### end Alembic commands ###
