"""update game models (cards, trades, enums, constraints)

Revision ID: debee84f8bd4
Revises: 0e847e32e26e
Create Date: 2026-04-27 18:32:51.357002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debee84f8bd4'
down_revision = '0e847e32e26e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('rarity', sa.Enum('common', 'uncommon', 'rare', 'legendary', 'master', name='cardrarity'), nullable=False),
    sa.Column('type', sa.Enum('movement', 'survival', 'combat', 'utility', 'debuff', name='cardtype'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('max_in_deck', sa.Integer(), nullable=False),
    sa.CheckConstraint('max_in_deck > 0', name='check_max_in_deck_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_name'), ['name'], unique=True)

    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deck_user_id'), ['user_id'], unique=False)

    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='tradestatus'), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('uses_remaining', sa.Integer(), nullable=False),
    sa.Column('tradable', sa.Boolean(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_card_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_card_user_id'), ['user_id'], unique=False)

    op.create_table('deck_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'card_id', name='unique_card_per_deck')
    )
    with op.batch_alter_table('deck_card', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deck_card_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deck_card_deck_id'), ['deck_id'], unique=False)

    op.create_table('trade_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('user_card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trade.id'], ),
    sa.ForeignKeyConstraint(['user_card_id'], ['user_card.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'user_card_id', name='unique_trade_card')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    op.drop_table('trade_card')
    with op.batch_alter_table('deck_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_card_deck_id'))
        batch_op.drop_index(batch_op.f('ix_deck_card_card_id'))

    op.drop_table('deck_card')
    with op.batch_alter_table('user_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_card_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_card_card_id'))

    op.drop_table('user_card')
    op.drop_table('trade')
    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deck_user_id'))

    op.drop_table('deck')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_name'))

    op.drop_table('card')
    # ### end Alembic commands ###
