"""Modified UserCard to allow for locking cards from play, and added nullable flags

Revision ID: e43a86e2150d
Revises: debee84f8bd4
Create Date: 2026-04-29 00:11:39.272612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43a86e2150d'
down_revision = 'debee84f8bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protected', sa.Boolean(), nullable=False))
        batch_op.alter_column('tradable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('locked',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_card', schema=None) as batch_op:
        batch_op.alter_column('locked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('tradable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('protected')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('creation_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
