"""empty message

Revision ID: eb7084117355
Revises: f15bb47f3a5a
Create Date: 2026-05-15 17:47:25.678562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7084117355'
down_revision = 'f15bb47f3a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('gold_collected', sa.Integer(), nullable=False),
    sa.Column('enemies_defeated', sa.Integer(), nullable=False),
    sa.Column('movement_cards_played', sa.Integer(), nullable=False),
    sa.Column('survival_cards_played', sa.Integer(), nullable=False),
    sa.Column('combat_cards_played', sa.Integer(), nullable=False),
    sa.Column('utility_cards_played', sa.Integer(), nullable=False),
    sa.Column('init_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_stats_init_at'), ['init_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_stats_user_id'), ['user_id'], unique=False)

    op.create_table('life_time_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('turns', sa.Integer(), nullable=False),
    sa.Column('gold_collected', sa.Integer(), nullable=False),
    sa.Column('enemies_defeated', sa.Integer(), nullable=False),
    sa.Column('movement_cards_played', sa.Integer(), nullable=False),
    sa.Column('survival_cards_played', sa.Integer(), nullable=False),
    sa.Column('combat_cards_played', sa.Integer(), nullable=False),
    sa.Column('utility_cards_played', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('life_time_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_life_time_stats_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_user_id'))

    op.drop_table('stats')
    with op.batch_alter_table('user_card', schema=None) as batch_op:
        batch_op.drop_column('protected')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protected', sa.BOOLEAN(), nullable=False))

    op.create_table('stats',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stats_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('life_time_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_time_stats_user_id'))

    op.drop_table('life_time_stats')
    with op.batch_alter_table('game_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_stats_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_stats_init_at'))

    op.drop_table('game_stats')
    # ### end Alembic commands ###
