"""added game table

Revision ID: f15bb47f3a5a
Revises: 5adb974016b9
Create Date: 2026-05-12 12:38:59.324585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15bb47f3a5a'
down_revision = '5adb974016b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_game'), ['game'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_user_id'), ['user_id'], unique=True)

    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stats_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stats_user_id'))

    op.drop_table('stats')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_game'))

    op.drop_table('game')
    # ### end Alembic commands ###
