"""add purchased flag to daily shop card

Revision ID: fb1e318a05ad
Revises: f15bb47f3a5a
Create Date: 2026-05-15 18:51:36.365407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1e318a05ad'
down_revision = 'f15bb47f3a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_shop_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchased', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_shop_card', schema=None) as batch_op:
        batch_op.drop_column('purchased')

    # ### end Alembic commands ###
